title: Rodrigo Jimenez
logo: /assets/img/Mugshot_Rodrigo.jpg
description: Data and business analyst with strong background in operations, logistics, and supply chain
show_downloads: false
theme: jekyll-theme-minimal



